### ISSUE TITLE
Max Memory Error

### ISSUE THREAD

**Issue by aglad-eng** [python-openxml/python-docx#1086]
I am trying to open and parse large word documents (50-100 Megabytes).  I consistently get an AttValue length too long error and I believe it is from the maximum xml parsing size referenced https://stackoverflow.com/questions/33828728/what-is-the-maximum-size-of-an-xml-file-when-using-pythons-lxml-etree

I wanted to confirm that my beliefs of the cause of the error are correct and if would be possible to increase the maximum size that python-docx can parse?

The trace back is listed below:

    self.doc = Document(self.path)
  File "C:\Python310\lib\site-packages\docx\api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "C:\Python310\lib\site-packages\docx\opc\package.py", line 130, in open
    Unmarshaller.unmarshal(pkg_reader, package, PartFactory)
  File "C:\Python310\lib\site-packages\docx\opc\package.py", line 198, in unmarshal
    parts = Unmarshaller._unmarshal_parts(
  File "C:\Python310\lib\site-packages\docx\opc\package.py", line 215, in _unmarshal_parts
    parts[partname] = part_factory(
  File "C:\Python310\lib\site-packages\docx\opc\part.py", line 191, in __new__
    return PartClass.load(partname, content_type, blob, package)
  File "C:\Python310\lib\site-packages\docx\opc\part.py", line 231, in load
    element = parse_xml(blob)
  File "C:\Python310\lib\site-packages\docx\oxml\__init__.py", line 28, in parse_xml
    root_element = etree.fromstring(xml, oxml_parser)
  File "src\lxml\etree.pyx", line 3252, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 2
lxml.etree.XMLSyntaxError: AttValue length too long, line 2, column 11006082

**Comment by wangqinl** [comment]
i have this question as yours .
Traceback (most recent call last):
  File "3wordgetjpg_error1.py", line 84, in <module>
    get_pictures(row[0],row[0][0:-5])
  File "3wordgetjpg_error1.py", line 52, in get_pictures
    doc = docx.Document(word_path)
  File "e:\Anaconda3\lib\site-packages\docx\api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "e:\Anaconda3\lib\site-packages\docx\opc\package.py", line 130, in open
    Unmarshaller.unmarshal(pkg_reader, package, PartFactory)
  File "e:\Anaconda3\lib\site-packages\docx\opc\package.py", line 199, in unmarshal
    pkg_reader, package, part_factory
  File "e:\Anaconda3\lib\site-packages\docx\opc\package.py", line 216, in _unmarshal_parts
    partname, content_type, reltype, blob, package
  File "e:\Anaconda3\lib\site-packages\docx\opc\part.py", line 191, in __new__
    return PartClass.load(partname, content_type, blob, package)
  File "e:\Anaconda3\lib\site-packages\docx\opc\part.py", line 231, in load
    element = parse_xml(blob)
  File "e:\Anaconda3\lib\site-packages\docx\oxml\__init__.py", line 28, in parse_xml
    root_element = etree.fromstring(xml, oxml_parser)
  File "src\lxml\etree.pyx", line 3237, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 2
lxml.etree.XMLSyntaxError: AttValue length too long, line 2, column 13284651

**Comment by scanny** [comment]
This means the value of a single attribute of a single element exceeds the maximum value in the neighborhood of 10 megabytes. It's plausible this is some sort of vector drawing where the whole drawing is stored as a single attribute.

This limitation is to protect against malicious files intended to produce denial of service (DOS) attacks.

That can be turned off but we're not going to turn that off for everyone because it would be a security exposure.

You could try monkey-patching the parser here:
https://github.com/python-openxml/python-docx/blob/master/src/docx/oxml/parser.py#L19-L20

with something like `etree.XMLParser({same-args}, ..., huge_tree=True)`, at your own risk of course. You'll need to call the `oxml_parser.set_element_class_lookup(element_class_lookup)` bit on the new parser instance too, to get the custom element classes hooked up.
