### ISSUE TITLE
Error AttributeError: 'builtin_function_or_method' object has no attribute 'seek'

### ISSUE THREAD

**Issue by beginnercoder123** [python-openxml/python-docx#1132]
Hello.I made program which interacts with MS Word.And i have error.
Traceback (most recent call last):
  File "D:\Python\Gui\email_name_salary_switcher.py", line 14, in func1
    document = docx.Document(path)
  File "D:\apps\Python\lib\site-packages\docx\api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "D:\apps\Python\lib\site-packages\docx\opc\package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "D:\apps\Python\lib\site-packages\docx\opc\pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "D:\apps\Python\lib\site-packages\docx\opc\phys_pkg.py", line 101, in __init__
    self._zipf = ZipFile(pkg_file, 'r')
  File "D:\apps\Python\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "D:\apps\Python\lib\zipfile.py", line 1330, in _RealGetContents
    endrec = _EndRecData(fp)
  File "D:\apps\Python\lib\zipfile.py", line 264, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'builtin_function_or_method' object has no attribute 'seek'
What can i do with it?

**Comment by scanny** [comment]
Closing inactive.
