### ISSUE TITLE
Exception module usage

### ISSUE THREAD

**Issue by amilawaobe** [python-openxml/python-docx#1149]
Environment Version 3.9.13

exception module usage :

from exceptions import PendingDeprecationWarning

This is giving problem.  Python 2's exceptions module has been moved, for consistency, to the builtin module. 

workable solution with this environment.

try:
    import exceptions
except ImportError:
    import builtins as exceptions

**Comment by Doodlinka** [comment]
Same here. How did a bug that makes the thing crash at import get into production in the first place?

**Comment by scanny** [comment]
I'm not getting the problem here. Can you be more specific?

`PendingDeprecationWarning` does not appear anywhere in the library and neither does `import exceptions`. How does this error arise and what is the stack trace?

Is it maybe in your own code?

**Comment by enaples** [comment]
Same here.

Python version 3.9.18

To reproduce just `pip install docx` and `import docx` and you will get 

> ModuleNotFoundError                       Traceback (most recent call last)

> ----> 1 import docx
> 
> File ~\anaconda3\envs\base\lib\site-packages\docx.py:30
>      27 except ImportError:
>      28     TAGS = {}
> ---> 30 from exceptions import PendingDeprecationWarning
>      31 from warnings import warn
>      33 import logging
> 
> ModuleNotFoundError: No module named 'exceptions'

**Comment by scanny** [comment]
Ah, okay, the thing is that `docx` is a (now-ancient) _separate_ package, actually a distant precursor to `python-docx` which is what you want to be installing:
```bash
pip install python-docx
```

**Comment by poa00** [comment]
If we use `pipreqs` to create `requirements.txt` from a script that starts with `import python-docx` it still outputs this error.  

```console
>>> pipreqs --force
```
```traceback
INFO: Not scanning for jupyter notebooks.
ERROR: Failed on file: C:\Users\User\src\pydot2doc\doc2dot.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\src\pydot2doc\.venv\Scripts\pipreqs.exe\__main__.py", line 7, in <module>
  File "c:\Users\User\src\pydot2doc\.venv\Lib\site-packages\pipreqs\pipreqs.py", line 609, in main
    init(args)
  File "c:\Users\User\src\pydot2doc\.venv\Lib\site-packages\pipreqs\pipreqs.py", line 533, in init
    candidates = get_all_imports(
                 ^^^^^^^^^^^^^^^^
  File "c:\Users\User\src\pydot2doc\.venv\Lib\site-packages\pipreqs\pipreqs.py", line 153, in get_all_imports
    raise exc
  File "c:\Users\User\src\pydot2doc\.venv\Lib\site-packages\pipreqs\pipreqs.py", line 139, in get_all_imports
    tree = ast.parse(contents)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    import python-docx
```

**Comment by scanny** [comment]
@poa00 the project/package name is `python-docx`, but the _importable_ package is `docx`. So this should be `import docx`, not import `python-docx`.

You
```bash
pip install python-docx
```
then you
```python
import docx
```

**Comment by poa00** [comment]
Thanks for getting back to me. Yes, that was originally the package name I had in my script.

For whatever reason, (I guess this is actually a `pipreqs` problem), when it parses a script that contains the line `import docx`, the older deprecated `docx` package is added as a dependency in the `requirements.txt` file rather than the newer `python-docx`.  Subsequently running:

```console
pip install -r requirements.txt
```
results in the older package being installed rather than the new one. As you advised above, manually installing the package does avoid this, but I will create an issue in the `pipreqs` for what it's worth.

**Comment by scanny** [comment]
The original (legacy) precursor package to `python-docx` was called `docx` and its main importable package was also `docx`.

There is no 1:1 relationship between an importable package name and the "project" name (pip install name). So if `pipreqs` is trying to infer the project from the imported package name it's going to be wrong sometimes. Like if you have `import PIL`, do you want `pip install PIL` (don't think so) or `pip install Pillow`?
