### ISSUE TITLE
mac m1 error : symbol not found in flat namespace

### ISSUE THREAD

**Issue by ByLiangCheng** [python-openxml/python-docx#1214]
Python version : 3.9
System : mac m1 12.5.1
Describe : 
Use this code
```
import docx
```
The following abnormal information is prompted
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zhangsan/project/python/test/venv/lib/python3.9/site-packages/docx/__init__.py", line 3, in <module>
    from docx.api import Document  # noqa
  File "/Users/zhangsan/project/python/test/venv/lib/python3.9/site-packages/docx/api.py", line 14, in <module>
    from docx.package import Package
  File "/Users/zhangsan/project/python/test/venv/lib/python3.9/site-packages/docx/package.py", line 9, in <module>
    from docx.opc.package import OpcPackage
  File "/Users/zhangsan/project/python/test/venv/lib/python3.9/site-packages/docx/opc/package.py", line 9, in <module>
    from docx.opc.part import PartFactory
  File "/Users/zhangsan/project/python/test/venv/lib/python3.9/site-packages/docx/opc/part.py", line 12, in <module>
    from .oxml import serialize_part_xml
  File "/Users/zhangsan/project/python/test/venv/lib/python3.9/site-packages/docx/opc/oxml.py", line 12, in <module>
    from lxml import etree
ImportError: dlopen(/Users/zhangsan/project/python/test/venv/lib/python3.9/site-packages/lxml/etree.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (_xmlFree)
```

**Comment by scanny** [comment]
Closing as stale/inactive.
