### ISSUE TITLE
Inconsistent document icons

### ISSUE THREAD

**Issue by 17Reset** [python-openxml/python-docx#1250]
Why does the icon of the generated document not match the chart created using office?
![微信截图_20230927152425](https://github.com/python-openxml/python-docx/assets/122418720/25f743b9-ea8d-4124-a479-da12f50d8693)

**Comment by scanny** [comment]
Hmm, never seen that before. What is the platform and other context?

**Comment by 17Reset** [comment]
Using Windows 11, the version of office on this machine is the latest version, but the version compatibility generated using Python-docx is inconsistent.

**Comment by 17Reset** [comment]
The red font is my comment, what I was trying to convey is the icon compatibility. Obviously the icons of the .docx document generated by python-docx are not compatible with the icons of using office word on windows.

**Comment by 17Reset** [comment]
Here's what I've found to be the likely cause, is it because the template is so old that the ico is inconsistent?
![微信截图_20231008003538](https://github.com/python-openxml/python-docx/assets/122418720/a2e8535e-3009-4952-9f87-3f674181a796)

**Comment by scanny** [comment]
Oh, okay, that makes more sense :)

Easy test would be to create your own "template" file, like the `new.docx` you have there, then open and save that and see what happens.
```python
document = Document("new.docx")
document.save("python-docx-from-template.docx")
```

**Comment by scanny** [comment]
This StackExchange question may provide a hint:
https://superuser.com/a/1774587

**Comment by 17Reset** [comment]
> Oh, okay, that makes more sense :)
> 
> Easy test would be to create your own "template" file, like the you have there, then open and save that and see what happens.`new.docx`
> 
> ```python
> document = Document("new.docx")
> document.save("python-docx-from-template.docx")
> ```

If you simply create a .docx file, this will report an error and not work:
Traceback (most recent call last):
  File "D:\Job\PL\python\xTest\text2docx\text2docx_test.py", line 38, in <module>
    tigergpt_MSWord_create('test.docx', [('unordered_list1', 'child item'),
  File "D:\Job\PL\python\xTest\text2docx\text2docx_test.py", line 15, in tigergpt_MSWord_create
    doc = Document(r"D:\Job\PL\python\xTest\text2docx\new.docx")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\docx\api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
                    ^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\docx\opc\package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\docx\opc\pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\docx\opc\phys_pkg.py", line 30, in __new__
    raise PackageNotFoundError(
docx.opc.exceptions.PackageNotFoundError: Package not found at 'D:\Job\PL\python\xTest\text2docx\new.docx'

**Comment by 17Reset** [comment]
> This StackExchange question may provide a hint: https://superuser.com/a/1774587

Of course, it's possible to change the ico thumbnails if you open the word manually and change it, but what I'd like is for the automated script to generate a .docx that is current with the latest office.

**Comment by scanny** [comment]
I was thinking the "Save Thumbnails" option as a hint. Like maybe that's turned on in the default template (or defaults to on if not set). So if you can find where that is set we could possibly set it off or whatever.
