### ISSUE TITLE
String with German Umlaut as core property

### ISSUE THREAD

**Issue by julmayer** [python-openxml/python-docx#186]
Hello,
I try to set a unicode string which contains a German Umlaut as document.core_properties.subject with the following code:
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

from docx import Document

document = Document()
document.core_properties.subject = u'Jürgen Somename'
```
But an error occurs:
```
Traceback (most recent call last):
  File "C:/test_docx.py", line 7, in <module>
    document.core_properties.subject = u'J��rgen Somename'
  File "C:\Python27\lib\site-packages\docx\opc\coreprops.py", line 123, in subject
    self._element.subject_text = value
  File "C:\Python27\lib\site-packages\docx\oxml\coreprops.py", line 184, in subject_text
    self._set_element_text('subject', value)
  File "C:\Python27\lib\site-packages\docx\oxml\coreprops.py", line 299, in _set_element_text
    value = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)
```
When I remove  **value = str(value)** from docx\oxml\coreprops.py line 299 everything works fine.
Is it necessary to change unicode to str in _set_element_text()?
Can I avoid this error by changing the encoding or something else?

Thanks

**Comment by julmayer** [comment]
For me it works to change line 299 in docx\oxml\coreprops.py to
```value = unicode(value)```

**Comment by scanny** [comment]
I don't think that solution is quite general because it doesn't specify an encoding. The `unicode()` function doesn't actually quite do what it sounds like. Also, there's no `unicode()` function in Python 3 IIRC.

However there's a function in python-pptx at pptx.compat.to_unicode() that should do the trick. I'd have to spend some quality time to look through the design notes and tests to be sure, but if someone wants to transplant that and get it working with tests I'd be open to a patch.
