### ISSUE TITLE
Style Names containing quotation marks

### ISSUE THREAD

**Issue by incredibleharry** [python-openxml/python-docx#246]
These seem to cause errors when referencing them (but not when adding them)

For example:
Body Text First Indent 2"
Hang.5"

for sy in toReview.styles:
        newstyle = outputDoc_styles.add_style(sy.name, sy.type)  ##this works
        newfont = outputDoc_styles[sy.name].font       ##this crashes

 Traceback (most recent call last):
...
  File "/usr/local/lib/python3.4/dist-packages/docx/styles/styles.py", line 44, in __getitem__
    style_elm = self._element.get_by_name(BabelFish.ui2internal(key))
  File "/usr/local/lib/python3.4/dist-packages/docx/oxml/styles.py", line 343, in get_by_name
    return self.xpath(xpath)[0]
  File "/usr/local/lib/python3.4/dist-packages/docx/oxml/xmlchemy.py", line 751, in xpath
    xpath_str, namespaces=nsmap
  File "lxml.etree.pyx", line 1507, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:52198)
  File "xpath.pxi", line 307, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:152124)
  File "xpath.pxi", line 227, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:151097)
  File "xpath.pxi", line 212, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:150896)
lxml.etree.XPathEvalError: Invalid predicate

Anyways, I can work around this by changing the " to a ' with str.replace but maybe this is something that is easily fixed?

**Comment by scanny** [comment]
Just out of curiosity, why do you need quotation marks in your style?

**Comment by incredibleharry** [comment]
I am trying to copy one document's formatting (including styles) to another, and the source document uses these style names (where the quote means inches).

**Comment by scanny** [comment]
Ah, got it. It sounds like the double quote needs to be escaped so XPath doesn't interpret it as an end of string or whatever. Try substituting the double quote with '&quot;' and see if that works. If it does, I expect that's a pretty sure sign the string value needs escaping before being sent to XPath.

**Comment by incredibleharry** [comment]
I think that's right, although not sure what you mean on by substituting the double quote with '"' -- it does work when I replace with a single quote as below.

    for sy in toReview.styles:
        newstyle = outputDoc_styles.add_style(sy.name.replace('"',"'"), sy.type)
        newfont = outputDoc_styles[sy.name.replace('"',"'")].font

**Comment by scanny** [comment]
Sorry, that escaping works too well! :) what I typed was ' & q u o t ; ' (with extra spacing this time so it doesn't get swallowed in rendering :) You can see it if you go into edit mode on that comment (although that might only be available to me, I'm not sure).

If that works, you should be able to escape it in one surrounding call using `escape()` if I recall correctly. Just search on 'python HTML OR XML escape'. I think it's in xml.sax.utils or something like that.

To be frank, this isn't likely to get fixed anytime soon. We don't have any active contributers at the moment. Everyone likes using it, but very few (read none) want to take the time to improve it :)
