### ISSUE TITLE
table style not working properly

### ISSUE THREAD

**Issue by mahloun** [python-openxml/python-docx#313]
I have some difficulties setting a style for tables.

I look into the `styles.xml` to find exactly what string I have to copy to my code:

```xml
...
<w:name w:val="Grid Table 7 Colorful Accent 1"/>
...
```

However, it's impossible to set it:
```python
>>> from docx import Document
>>> doc = Document()
>>> table = doc.add_table(1, 1)
>>> table.style = "Grid Table 7 Colorful Accent 1"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/docx/table.py", line 134, in style
    style_or_name, WD_STYLE_TYPE.TABLE
  File "/usr/local/lib/python3.4/dist-packages/docx/parts/document.py", line 76, in get_style_id
    return self.styles.get_style_id(style_or_name, style_type)
  File "/usr/local/lib/python3.4/dist-packages/docx/styles/styles.py", line 113, in get_style_id
    return self._get_style_id_from_name(style_or_name, style_type)
  File "/usr/local/lib/python3.4/dist-packages/docx/styles/styles.py", line 143, in _get_style_id_from_name
    return self._get_style_id_from_style(self[style_name], style_type)
  File "/usr/local/lib/python3.4/dist-packages/docx/styles/styles.py", line 57, in __getitem__
    raise KeyError("no style with name '%s'" % key)
KeyError: "no style with name 'Grid Table 7 Colorful Accent 1'"
>>>
```

What is wrong?

**Comment by scanny** [comment]
I expect you're finding a so-called "latent style" rather than an actual style definition, but would need to see more of the XML to know.

You can enumerate the available styles in the document with something like:

```python
for style in document.styles:
    print(style.name)
```

This will generally be easier and more reliable than scanning the styles.xml unless you know a little more about what you're looking for.

Make sure you've read this page (and the one following it) in the documentation to understand a few of the gotchas with styles:
http://python-docx.readthedocs.io/en/latest/user/styles-understanding.html

**Comment by scanny** [comment]
Glad you got it working :)
