### ISSUE TITLE
Error when opening existing .docx/.odt document

### ISSUE THREAD

**Issue by svartkanin** [python-openxml/python-docx#316]
I receive an error when trying to open any .docx or .odt file:

Traceback (most recent call last):
  File "document.py", line 6, in <module>
    document = Document('demo.odt')
  File "/usr/local/lib/python2.7/dist-packages/python_docx-0.8.5-py2.7.egg/docx/api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "/usr/local/lib/python2.7/dist-packages/python_docx-0.8.5-py2.7.egg/docx/opc/package.py", line 116, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/usr/local/lib/python2.7/dist-packages/python_docx-0.8.5-py2.7.egg/docx/opc/pkgreader.py", line 33, in from_file
    content_types = _ContentTypeMap.from_xml(phys_reader.content_types_xml)
  File "/usr/local/lib/python2.7/dist-packages/python_docx-0.8.5-py2.7.egg/docx/opc/phys_pkg.py", line 121, in content_types_xml
    return self.blob_for(CONTENT_TYPES_URI)
  File "/usr/local/lib/python2.7/dist-packages/python_docx-0.8.5-py2.7.egg/docx/opc/phys_pkg.py", line 108, in blob_for
    return self._zipf.read(pack_uri.membername)
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named '[Content_Types].xml' in the archive"

I saw that when creating a document with python-docx then the zip file of the document creates the content xml file with the name like '[Content_Types].xml'
But when creating a file with libreOffice, then the content file in the zip file is named 'content.xml'!

**Comment by scanny** [comment]
`python-docx` supports the OpenXML file format (.docx), not the OpenDocument format (.odt). The zip archive member `content.xml` is characteristic of the latter.
