### ISSUE TITLE
How to add an argument as file name?

### ISSUE THREAD

**Issue by rhenrique** [python-openxml/python-docx#386]
Hello,

I'm trying to add an argument as file name but I'm not able:

 python createUser.py test.docx
```
Traceback (most recent call last):
  File "createUser.py", line 9, in <module>
    document = Document(f)
  File "C:\PYTHON27\lib\site-packages\python_docx-0.8.6-py2.7.egg\docx\api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "C:\PYTHON27\lib\site-packages\python_docx-0.8.6-py2.7.egg\docx\opc\package.py", line 116, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "C:\PYTHON27\lib\site-packages\python_docx-0.8.6-py2.7.egg\docx\opc\pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "C:\PYTHON27\lib\site-packages\python_docx-0.8.6-py2.7.egg\docx\opc\phys_pkg.py", line 101, in __init__
    self._zipf = ZipFile(pkg_file, 'r')
  File "C:\PYTHON27\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "C:\PYTHON27\lib\zipfile.py", line 813, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

Code:

```
script, fl = argv

f = open(fl, 'rb')
document = Document(f)
```

Is that possible?
Thanks

**Comment by scanny** [comment]
If you want to open a Word document, just use the path, don't open the file first.

```python
word_file_path = argv[1]
document = Document(word_file_path)
```

**Comment by rhenrique** [comment]
Hey @scanny, thanks.

Actually, I dont' want open a WORD Document, I want to create it with the argument and write on it instead of to save it with a specific name (document.save('demo.docx')).
$ python python-docx.docx lalalala.docx

So, my final file will be named "lalalala.docx"
I tried to do what you said, but it gives me error too.

**Comment by rhenrique** [comment]
Oh yeah, I got it now.

```
fl = argv[1]

document = Document()
open(fl, 'w')
```

Thanks :)
