### ISSUE TITLE
Error while importing from docx (aka python-docx)

### ISSUE THREAD

**Issue by zmeiau** [python-openxml/python-docx#402]
hi there,

I've installed python-docx via pip install on W7-64 platform with Python3.6 installed.
When importing from docx getting error messages:
<<<
SyntaxError: invalid syntax
>>> from docx import Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\docx\__init__.py", line 3, in <module>
    from docx.api import Document  # noqa
  File "C:\Python36\lib\site-packages\docx\api.py", line 14, in <module>
    from docx.package import Package
  File "C:\Python36\lib\site-packages\docx\package.py", line 11, in <module>
    from docx.opc.package import OpcPackage
  File "C:\Python36\lib\site-packages\docx\opc\package.py", line 12, in <module>
    from .part import PartFactory
  File "C:\Python36\lib\site-packages\docx\opc\part.py", line 12, in <module>
    from .oxml import serialize_part_xml
  File "C:\Python36\lib\site-packages\docx\opc\oxml.py", line 12, in <module>
    from lxml import etree
ImportError: DLL load failed: The specified procedure could not be found.
>>>

There are no outdated Python packages - see output below

<<<
C:\Users\me>pip list -o
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a
 format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
C:\Users\me>
>>>

All dependencies seems to be in place  - see output below

<<<
C:\Users\me>pip list python-docx
DEPRECATION: The default format will swit
 format=(legacy|columns) in your pip.conf
astroid (1.5.3)
autopep8 (1.3.2)
colorama (0.3.9)
isort (4.2.13)
lazy-object-proxy (1.3.1)
lxml (3.8.0)
mccabe (0.6.1)
pip (9.0.1)
pycodestyle (2.3.1)
pylint (1.7.1)
python-docx (0.8.6)
setuptools (36.0.1)
six (1.10.0)
wrapt (1.10.10)
C:\Users\me>
>>>

Your help will be aprpeciated

**Comment by scanny** [comment]
It looks like you're missing `lxml` or one of its dependencies.

Try installing from a binary distribution: http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

https://stackoverflow.com/questions/37279399/python-pptx-for-python-3-5-1/37280209#37280209

https://github.com/scanny/python-pptx/issues/233

**Comment by alinabrinza95** [comment]
Hello, could you tell me if your problem was solved installing lxml?
Because i have it installed, but i have the same issue.
Thank you.

**Comment by manavmehra96** [comment]
I have the same issue , installed Lxml as well. The problem still persists

**Comment by emptyroom** [comment]
Has anyone found a fix for this issue? Using Python 3.6 and lxml 2.3.2

**Comment by scanny** [comment]
This is not a problem with `python-docx`. Rather it is a problem getting `lxml` installed. The test is seeing if you get the same error by just having the line:

```python
import lxml
```

instead of or before the first `from docx import ...` line. It sounds like perhaps there is a library dependency like `lib2xml` or `libxslt` that is not satisfied for the `lxml` install.

Try searching Google on `lxml ImportError: DLL load failed` and see if you can find a solution there.

**Comment by usamarana00** [comment]
try typing this command " pip3 install python-docx " on powershell first

**Comment by scanny** [comment]
Closed as inactive.
