### ISSUE TITLE
KeyError: "no style with name 'BODY_TEXT (-67)'"

### ISSUE THREAD

**Issue by EduardoWillians** [python-openxml/python-docx#420]
>>> from docx import Document
>>> from docx.enum.style import WD_STYLE
>>> document = Document()
>>> styles = document.styles
>>> style = styles[WD_STYLE.BODY_TEXT]
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    style = styles[WD_STYLE.BODY_TEXT]
  File "C:\Python\Python36-32\lib\site-packages\docx\styles\styles.py", line 57, in __getitem__
    raise KeyError("no style with name '%s'" % key)
KeyError: "no style with name 'BODY_TEXT (-67)'"

What's wrong?

**Comment by mmichaelis** [comment]
Experienced the same (some years later): Although it is part of the documentation, the example just does not work:

https://github.com/python-openxml/python-docx/blob/0cf6d71fb47ede07ecd5de2a8655f9f46c5f083d/src/docx/enum/style.py#L7-L24

Using the names as plain strings, works, though, like:

```python
from docx import Document

document = Document()
styles = document.styles
style = styles['Body Text']
```
