### ISSUE TITLE
IndexError when adding table

### ISSUE THREAD

**Issue by lux-lth** [python-openxml/python-docx#514]
I'm opening a docx, and trying to add a table but python-docx crashed with this message :

```
Traceback (most recent call last):
  File "styler.py", line 4, in <module>
    document.add_table(rows=10,cols=10)
  File "/usr/local/lib/python3.6/site-packages/docx/document.py", line 99, in add_table
    table = self._body.add_table(rows, cols, self._block_width)
  File "/usr/local/lib/python3.6/site-packages/docx/document.py", line 184, in _block_width
    section = self.sections[-1]
  File "/usr/local/lib/python3.6/site-packages/docx/section.py", line 25, in __getitem__
    sectPr = self._document_elm.sectPr_lst[key]
IndexError: list index out of range
```

Looking at the code it seems that if there are no sections in the document, the library crashes.

So I created a section before creating the table :

```
from docx import Document

document = Document('report-3.docx')
document.add_section()
document.add_table(rows=10,cols=10)
```

But it crashes again :

```
Traceback (most recent call last):
  File "styler.py", line 6, in <module>
    document.add_table(rows=10,cols=10)
  File "/usr/local/lib/python3.6/site-packages/docx/document.py", line 99, in add_table
    table = self._body.add_table(rows, cols, self._block_width)
  File "/usr/local/lib/python3.6/site-packages/docx/document.py", line 186, in _block_width
    section.page_width - section.left_margin - section.right_margin
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

Isn't there a way to add a style to the document without adding a table.

**Comment by scanny** [comment]
How was the original document created? A default Word document has one section and `python-docx` assumes there is at least the one section (that includes the whole document if there are no other sections).

**Comment by lux-lth** [comment]
The document was created by pandoc. Converting a rst file to docx.

[http://pandoc.org](http://pandoc.org)

**Comment by scanny** [comment]
If you open 'report-3.docx' with Word and then save it, before opening it with `python-docx`, does it still raise the indicated exception?

**Comment by lux-lth** [comment]
Hello, thank you for your answers, I'll try that tomorrow.

I solved my issue using pandoc --data-source option, which basically paste the docx styles of one document into the generated document.

But I'll have uses for python-docx, to create the main structure of the documents. I try tomorrow and let you know. Thanks again.

**Comment by LeperGnome** [comment]
Issue is still opened, and I wonder if there is a way to resolve it using _python-docx_
