### ISSUE TITLE
Exception when reading strange table

### ISSUE THREAD

**Issue by RolandColored** [python-openxml/python-docx#531]
Hey there,

we stumbled upon a strange docx file in production.

[broken_table.docx](https://github.com/python-openxml/python-docx/files/2257782/broken_table.docx)

When trying to read all cells in this table, an exception is thrown:
```
from docx import Document

with open('broken_table.docx', 'rb') as fh:
    document = Document(fh)
    print([cell.text for cell in document.tables[0].rows[0].cells])
```
```
Traceback (most recent call last):
  File "./broken_table.py", line 5, in <module>
    print([cell.text for cell in document.tables[0].rows[0].cells])
  File "./venv/lib/python3.6/site-packages/docx/table.py", line 384, in cells
    return tuple(self.table.row_cells(self._index))
  File "./venv/lib/python3.6/site-packages/docx/table.py", line 106, in row_cells
    return self._cells[start:end]
  File "./venv/lib/python3.6/site-packages/docx/table.py", line 173, in _cells
    cells.append(cells[-col_count])
IndexError: list index out of range
```
We are using version 0.8.6 with Python 3.6 and the error occurs on Linux and macOS.

**Comment by scanny** [comment]
Fixed in v1.1.1 circa Apr 30, 2024.
