### ISSUE TITLE
raised unexpected: PackageNotFoundError("Package not found at path)

### ISSUE THREAD

**Issue by sskadit** [python-openxml/python-docx#557]
```
 raised unexpected: PackageNotFoundError("Package not found at '/Users/sskadit/Office/nlpondec2017/newonenv/src/newproject/DATA/C++ Developer/RVAravind_4.doc'",)
Traceback (most recent call last):
  File "/Users/sskadit/Office/nlpondec2017/newenv/src/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/sskadit/Office/nlpondec2017/newenv/src/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/sskadit/Office/nlpondec2017/newonenv/src/newproject/new/tasks.py", line 78, in test
    doc = docx.Document(inp)
  File "/Users/sskadit/Office/nlpondec2017/newenv/src/lib/python3.4/site-packages/docx/api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "/Users/sskadit/Office/nlpondec2017/newenv/src/lib/python3.4/site-packages/docx/opc/package.py", line 116, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/Users/sskadit/Office/nlpondec2017/newenv/src/lib/python3.4/site-packages/docx/opc/pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/Users/sskadit/Office/nlpondec2017/newenv/src/lib/python3.4/site-packages/docx/opc/phys_pkg.py", line 31, in __new__
    "Package not found at '%s'" % pkg_file
docx.opc.exceptions.PackageNotFoundError: Package not found at '/Users/sskadit/Office/nlpondec2017/newonenv/src/newproject/DATA/C++ Developer/RVAravind_4.doc'
```

I found the absolute path and relative path to be the same using this in django celery cron to read the doc files 

Mac OSX
Python 3.4

**Comment by timothydkiser** [comment]
Any updates here?

**Comment by scanny** [comment]
There's not enough information here to indicate an error. There are a variety of reasons why this error can arise. In this case it looks like you're trying to open a pre-Office-2007 ".doc" file (rather than a .docx file). `python-docx` only supports the latter (which is an XML format rather than binary).

**Comment by AhmadSakor** [comment]
You have to write something in the docx file. Then the package can recognize it.

**Comment by konradbachusz** [comment]
I have the same issue. My file is .docx and has content in it.

**Comment by aqg8017** [comment]
same issue as [konradbachusz-zz](https://github.com/konradbachusz-zz)

**Comment by chaoStart** [comment]
> I have the same issue. My file is .docx and has content in it.

how to  resolve the problem？ My file is .docx,but it's also has the problem " docx.opc.exceptions.PackageNotFoundError: Package not found at './paper2.docx'"
