### ISSUE TITLE
Error with paragraph.style = 'List Bullet'!

### ISSUE THREAD

**Issue by ninhnvt** [python-openxml/python-docx#570]
from docx import Document

document1 = Document('example1.docx')
table = document1.tables[0]
document2 = Document()
paragraph = document2.add_paragraph('Lorem ipsum dolor sit ame2.')
print("document2:",type(document2))
#Run Ok
paragraph.style = 'List Bullet'
print("paragraph: ",type(paragraph))
cell = table.cell(7,1)
print("cell: ",type(cell))
print(table.style)
paragraph1 = cell.add_paragraph("abc")
print("paragraph1: ",type(paragraph1))
# Run not OK
paragraph1.style = 'List Bullet'
document1.save('example1.docx')

Output:

Traceback (most recent call last):
  File "C:\Python37\ccm_template\test.py", line 44, in <module>
    paragraph1.style = 'List Bullet'
  File "C:\Python37\lib\site-packages\docx\text\paragraph.py", line 112, in styl
e
    style_or_name, WD_STYLE_TYPE.PARAGRAPH
  File "C:\Python37\lib\site-packages\docx\parts\document.py", line 76, in get_s
tyle_id
    return self.styles.get_style_id(style_or_name, style_type)
  File "C:\Python37\lib\site-packages\docx\styles\styles.py", line 113, in get_s
tyle_id
    return self._get_style_id_from_name(style_or_name, style_type)
  File "C:\Python37\lib\site-packages\docx\styles\styles.py", line 143, in _get_
style_id_from_name
    return self._get_style_id_from_style(self[style_name], style_type)
  File "C:\Python37\lib\site-packages\docx\styles\styles.py", line 57, in __geti
tem__
    raise KeyError("no style with name '%s'" % key)
KeyError: "no style with name 'List Bullet'"

**Comment by ch-rigu** [comment]
Hi, i'm facing the same issue, this happen when the I use a .docx file as template, and the language is in spanish. If I try List bullet without a .docx as template it works good.
Any idea how to get a workaround on this ?

Cheers.

**Comment by scanny** [comment]
Try listing your style names and pick the one to match; it might be in Spanish:

```
for style in document.styles:
    print("style.name == %s" % style.name)
```

**Comment by ch-rigu** [comment]
Thanks!, I realized that my template .docx was missing almost all styles!, just some a few styles in spanish was existing....
I created a new empty docx with python-docx and then I added the extra style that I need. 
Now my base template is fully populated with the styles :)
Thanks.

**Comment by scanny** [comment]
Closing as resolved.
