### ISSUE TITLE
Need support for python 2.6

### ISSUE THREAD

**Issue by vijay1275** [python-openxml/python-docx#609]
python-docx is not compatible with python 2.6

From 0.8.8 release of python-docx, seeing below error

Python 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from docx import Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/docx/__init__.py", line 3, in <module>
    from docx.api import Document  # noqa
  File "/usr/lib/python2.6/site-packages/docx/api.py", line 14, in <module>
    from docx.package import Package
  File "/usr/lib/python2.6/site-packages/docx/package.py", line 9, in <module>
    from docx.opc.package import OpcPackage
  File "/usr/lib/python2.6/site-packages/docx/opc/package.py", line 116
    partnames = {part.partname for part in self.iter_parts()}
                                 ^
SyntaxError: invalid syntax

**Comment by scanny** [comment]
Closed as inactive.
