### ISSUE TITLE
Python Docx to exe error

### ISSUE THREAD

**Issue by SuchithSridhar** [python-openxml/python-docx#654]
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "CompilerGui.py", line 259, in <lambda>
    done = ttk.Button(window, text="Compile", command=lambda:finish(texts, window, search_folder))
  File "CompilerGui.py", line 210, in finish
    cb.the_main(q_list, values)
  File "CompilerBase.py", line 323, in the_main
    file_written = write_docx(values_dict, file_to_write)
  File "CompilerBase.py", line 100, in write_docx
    my_docx = docx.Document()
  File "site-packages\docx\api.py", line 25, in Document
  File "site-packages\docx\opc\package.py", line 128, in open
  File "site-packages\docx\opc\pkgreader.py", line 32, in from_file
  File "site-packages\docx\opc\phys_pkg.py", line 31, in __new__
docx.opc.exceptions.PackageNotFoundError: Package not found at 'C:\Users\LENOVO\AppData\Local\Temp\_MEI92522\docx\templates\default.docx'

It Gives me the error only after i have converted it to an exe, works fine as a .py file
i tried to find the file missing and replace it but it still didnt work

**Comment by SuchithSridhar** [comment]
I figured out the fix to this !
https://youtu.be/A9PzLI54SY8
