### ISSUE TITLE
when save document, i encountered UnicodeEncodeError

### ISSUE THREAD

**Issue by zaojiahua** [python-openxml/python-docx#818]
my environment is centos, python3.6, when save document, encountered the following error, how can i fix it.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/web/betaquantity_server/betaquantity/celery/question_pool/tasks.py", line 108, in run
    self.output_exercise_book(past_question_collection)
  File "/web/betaquantity_server/betaquantity/celery/question_pool/tasks.py", line 246, in output_exercise_book
    self.document_book.save(book_name)
  File "/usr/local/lib/python3.6/site-packages/docx/document.py", line 135, in save
    self._part.save(path_or_stream)
  File "/usr/local/lib/python3.6/site-packages/docx/parts/document.py", line 111, in save
    self.package.save(path_or_stream)
  File "/usr/local/lib/python3.6/site-packages/docx/opc/package.py", line 172, in save
    PackageWriter.write(pkg_file, self.rels, self.parts)
  File "/usr/local/lib/python3.6/site-packages/docx/opc/pkgwriter.py", line 32, in write
    phys_writer = PhysPkgWriter(pkg_file)
  File "/usr/local/lib/python3.6/site-packages/docx/opc/phys_pkg.py", line 141, in __init__
    self._zipf = ZipFile(pkg_file, 'w', compression=ZIP_DEFLATED)
  File "/usr/lib64/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-28: ordinal not in range(128)

**Comment by linuxkd** [comment]
You probably need to sanitize the input to make sure there aren't non printable/control characters in the input data. I used something like this:

```
def remove_control_characters(s):
    """Remove control/nonprintable characters."""
    return "".join(
        ch
        for ch in s
        if (unicodedata.category(ch)[0] != "C" or "\r" in ch or "\n" in ch)
    )
```
