### ISSUE TITLE
Cannot run the python code using cmd

### ISSUE THREAD

**Issue by karanthapa14** [python-openxml/python-docx#819]
Traceback (most recent call last):
  File "xxx.py", line 1, in <module>
    from docx import Document
  File "C:\ProgramData\Anaconda3\lib\site-packages\docx\__init__.py", line 3, in <module>
    from docx.api import Document  # noqa
  File "C:\ProgramData\Anaconda3\lib\site-packages\docx\api.py", line 14, in <module>
    from docx.package import Package
  File "C:\ProgramData\Anaconda3\lib\site-packages\docx\package.py", line 9, in <module>
    from docx.opc.package import OpcPackage
  File "C:\ProgramData\Anaconda3\lib\site-packages\docx\opc\package.py", line 9, in <module>
    from docx.opc.part import PartFactory
  File "C:\ProgramData\Anaconda3\lib\site-packages\docx\opc\part.py", line 12, in <module>
    from .oxml import serialize_part_xml
  File "C:\ProgramData\Anaconda3\lib\site-packages\docx\opc\oxml.py", line 12, in <module>
    from lxml import etree
ImportError: DLL load failed: The specified module could not be found.

**Comment by scanny** [comment]
This is a problem with your `lxml` install, not `python-docx`. Please post support questions on StackOverflow using the "python-docx" tag. This issues list is only for feature requests and suspected bugs. This particular question has been asked and answered many times and is available on search.
