### ISSUE TITLE
python-docx is not compatible with lxml 4.5.2

### ISSUE THREAD

**Issue by Sharku2011** [python-openxml/python-docx#859]
It throws "ImportError: cannot import name 'etree' from 'lxml' (~\Python\Python38\lib\site-packages\lxml\__init__.py)"

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\docx\__init__.py", line 3, in <module>
    from docx.api import Document  # noqa
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\docx\api.py", line 14, in <module>
    from docx.package import Package
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\docx\package.py", line 9, in <module>
    from docx.opc.package import OpcPackage
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\docx\opc\package.py", line 9, in <module>
    from docx.opc.part import PartFactory
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\docx\opc\part.py", line 12, in <module>
    from .oxml import serialize_part_xml
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\docx\opc\oxml.py", line 12, in <module>
    from lxml import etree

**Comment by Sharku2011** [comment]
After downgrade lxml to versio 4.5.1, it works well

**Comment by Jalkhov** [comment]
In my case:

python 3.8.10 x32 Bits 4.5.1 version doesn't work, ihave used `4.9.2`
