### ISSUE TITLE
how to extract txt  or zip file from OLE  in docx? 

### ISSUE THREAD

**Issue by wulanshi123** [python-openxml/python-docx#913]
I want to extract a txt or zip ole file from docx by python , but the procedure reports "OSError: file not found" message, i just want to extract the txt or zip file ,how to do ?   pls help me , thank you !!

this following is my code  and running error result.
===============================================================
import olefile
from zipfile import ZipFile

def get_ole(filename):

    # Try to open the document as ZIP file
    with ZipFile(filename, "r") as zip:

        # Find files in the word/embeddings folder of the ZIP file
        for entry in zip.infolist():
            if not entry.filename.startswith("word/embeddings/"):
                continue

            # Try to open the embedded OLE file
            with zip.open(entry.filename) as f:
                if not olefile.isOleFile(f):
                    continue

                ole = olefile.OleFileIO(f)

                print(ole.listdir())
                print("txt id:" + ole.root.clsid)

                print("===========================")
				# if file name is txt file or a ZIP file, how to extract the file 
                bin_data = ole.openstream("entry").read()
                with open("bin_1.tx", "wb") as output_file:
                    output_file.write(bin_data)  # i wang to generate the ole to a txt file. 

if __name__ == '__main__':
	#file_name = sys.argv[1]
    get_ole("attachment_txt.docx")
    
    
========================running result====================================
PS D:\PythonProject\getOle> & "D:/Program Files/Python/Python37/python.exe" d:/PythonProject/getOle/test.py
[['\x01CompObj'], ['\x01Ole10Native'], ['\x03ObjInfo']]
===========================
txt id:0003000C-0000-0000-C000-000000000046
Traceback (most recent call last):
  File "d:/PythonProject/getOle/test.py", line 55, in <module>
    get_ole("attachment_txt.docx")
  File "d:/PythonProject/getOle/test.py", line 46, in get_ole
    bin_data = ole.openstream("entry").read()
  File "D:\Program Files\Python\Python37\lib\site-packages\olefile\olefile.py", line 1907, in openstream
    sid = self._find(filename)
  File "D:\Program Files\Python\Python37\lib\site-packages\olefile\olefile.py", line 1887, in _find
    raise IOError("file not found")
OSError: file not found
PS D:\PythonProject\getOle>

**Comment by wulanshi123** [comment]
@scanny  Hi, my friend ,can you help me ? thank you !

**Comment by alitrack** [comment]
here is a solution 

```PYTHON
import olefile
from zipfile import ZipFile
def get_ole(filename):
    with ZipFile(filename, "r") as zip:
        for entry in zip.infolist():
            if not entry.filename.startswith("word/embeddings/"):
                continue
            with zip.open(entry.filename) as f:
                if not olefile.isOleFile(f):
                    continue

                with olefile.OleFileIO(f) as ole:
                    print(ole.listdir())
                   #return [['\x01Ole'], ['\x03ObjInfo'], ['package']] and the in this case the data is in 'package'
                    bin_data = ole.openstream("package").read()
                    fn = entry.filename.replace("word/embeddings/","")
                    with open(fn, "wb") as output_file:
                        output_file.write(bin_data)
if __name__ == '__main__':
    get_ole("test.docx")

```
for details, please visit [extract excel attachment from word documents](https://mp.weixin.qq.com/s?__biz=MzU1NTg2ODQ5Nw==&mid=2247488277&idx=1&sn=e10110f2af70428667802cd6252fe137&chksm=fbcc9b2bccbb123deb0c65652b75711c55eea6b9b1b0df94edaedb058886f10e5bff22132d3c&token=1298421283&lang=zh_CN#rd)
