### ISSUE TITLE
Single character modify style

### ISSUE THREAD

**Issue by ymmeng** [python-openxml/python-docx#988]
How can I modify the style of individual characters?

**Comment by scanny** [comment]
For a character or sequence of characters to have different font formatting than the text on either side, those characters need to be in a distinct run.

The code here will isolate a sequence of characters into its own run, after which you can format that run as desired:  
https://github.com/python-openxml/python-docx/issues/980

**Comment by ymmeng** [comment]
Thank you for your reply, but I encountered the following errors during operation:
```sh
Traceback (most recent call last):

File "test.py", line 114, in <module>

isolate_ run(par, 0, len(par.text))

File "test.py", line 88, in isolate_ run

r, r_ idx, start, end = advance_ to_ run_ containing_ start(start, end)

File "test.py", line 46, in advance_ to_ run_ containing_ start

r_ ends = tuple(itertools.accumulate(len(r.text) for r in rs)) + (0,)

NameError: name 'itertools' is not defined
```
Do you have any use examples for your code? I'd like to refer to it. I may be powerless for your current answer.
